"""add height weight deity journal currency to characters

Revision ID: 18da8cfaf343
Revises: ad9063030fea
Create Date: 2026-05-13 15:45:54.056336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18da8cfaf343'
down_revision: Union[str, None] = 'ad9063030fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('height', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('weight', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('deity', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('journal', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('currency', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'currency')
    op.drop_column('characters', 'journal')
    op.drop_column('characters', 'deity')
    op.drop_column('characters', 'weight')
    op.drop_column('characters', 'height')
    # ### end Alembic commands ###
