"""add_species_lineage_size_choice_and_species_lineages

Revision ID: 929541d0651b
Revises: b4b8fca5bcf5
Create Date: 2026-05-09 08:15:19.416240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929541d0651b'
down_revision: Union[str, None] = 'b4b8fca5bcf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('species_lineage', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('species_size_choice', sa.String(), nullable=True))
    op.add_column('species', sa.Column('lineages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('species', 'lineages')
    op.drop_column('characters', 'species_size_choice')
    op.drop_column('characters', 'species_lineage')
    # ### end Alembic commands ###
