"""add source and notes to character_spells

Revision ID: ad9063030fea
Revises: 18c5735138ca
Create Date: 2026-05-13 10:08:59.814034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9063030fea'
down_revision: Union[str, None] = '18c5735138ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_spells', sa.Column('source', sa.String(), nullable=True))
    op.add_column('character_spells', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_spells', 'notes')
    op.drop_column('character_spells', 'source')
    # ### end Alembic commands ###
