"""add_owner_email_to_characters

Revision ID: b4b8fca5bcf5
Revises: f408a8e6773c
Create Date: 2026-05-08 08:23:13.827359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b8fca5bcf5'
down_revision: Union[str, None] = 'f408a8e6773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('owner_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'owner_email')
    # ### end Alembic commands ###
